version: "3.9"

services:
  django:
    build: .
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/bm8_api
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: pgdb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=bm152612
