version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/bm8
    ports:
      - "8000:8000"
   
# services:
#   django: 
#     build: .
#     container_name: django
#   db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:postgres_data:/var/lib/postgresql/data/
#     ports:
#       - "8000:8000"
#     environment:
#       - POSTGRES_NAME=bmtbl
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=bm152612
#     depends_on:
#       - db