[tool.black]
target-version = ['py36', 'py37', 'py38', 'py39']
line-length = 119
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | ./accounts/tests/factories/
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 119
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["django", "drf_yasg", "phonenumber_field", "rest_framework"]
