name: lint

on: [pull_request]

jobs:
  black-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
           python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  flake8-lint:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E203"
          exclude: "migrations/"
          max-line-length: "119"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
